version: "3.9"

services:
  haraka:
    image: ghcr.io/mr-karan/haraka:2.8.28
    restart: unless-stopped
    environment:
      - TZ=Asia/Kolkata
    ports:
      - "2525:2525"
    container_name: haraka
    volumes:
    # Uncomment this if you have a custom config directory to mount.
    # - ./config:/haraka/config:ro
    - ./data/haraka/smtp_logs:/smtp_logs
    - ./data/haraka/queue:/queue
